# Generated by Django 5.2.11 on 2026-02-19 14:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('adm1_name', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name1', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name2', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_pcode', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name1', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name2', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_pcode', models.CharField(blank=True, max_length=80, null=True)),
                ('valid_on', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('area_sqkm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cod_versio', models.CharField(blank=True, max_length=80, null=True)),
                ('lang', models.CharField(blank=True, max_length=80, null=True)),
                ('lang1', models.CharField(blank=True, max_length=80, null=True)),
                ('lang2', models.CharField(blank=True, max_length=80, null=True)),
                ('lang3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_ref_n', models.CharField(blank=True, max_length=80, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('center_lon', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'Counties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcounties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('adm2_name', models.CharField(blank=True, max_length=80, null=True)),
                ('adm2_name1', models.CharField(blank=True, max_length=80, null=True)),
                ('adm2_name2', models.CharField(blank=True, max_length=80, null=True)),
                ('adm2_name3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm2_pcode', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name1', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name2', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_name3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm1_pcode', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name1', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name2', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_name3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm0_pcode', models.CharField(blank=True, max_length=80, null=True)),
                ('valid_on', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('area_sqkm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cod_versio', models.CharField(blank=True, max_length=80, null=True)),
                ('lang', models.CharField(blank=True, max_length=80, null=True)),
                ('lang1', models.CharField(blank=True, max_length=80, null=True)),
                ('lang2', models.CharField(blank=True, max_length=80, null=True)),
                ('lang3', models.CharField(blank=True, max_length=80, null=True)),
                ('adm2_ref_n', models.CharField(blank=True, max_length=80, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('center_lon', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'verbose_name': 'Subcounty',
                'verbose_name_plural': 'Subcounties',
                'db_table': 'Subcounties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandUseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(blank=True, choices=[('long_rains', 'Long Rains'), ('short_rains', 'Short Rains')], max_length=20, null=True)),
                ('total_hectares', models.FloatField()),
                ('geoserver_link', models.URLField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landuse_records', to='landuse.counties')),
            ],
            options={
                'unique_together': {('county', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='LandUseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Crop', 'Crop'), ('Trees', 'Trees'), ('Building', 'Building'), ('Road', 'Road'), ('Shrub & Scrub', 'Shrub & Scrub'), ('Grass', 'Grass'), ('Water', 'Water'), ('Bare Ground', 'Bare Ground')], max_length=50)),
                ('hectares', models.FloatField()),
                ('percentage', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='landuse.landuserecord')),
            ],
        ),
    ]
