# Generated by Django 5.2.11 on 2026-02-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landuserecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='landuserecord',
            name='level',
            field=models.CharField(choices=[('county', 'County'), ('subcounty', 'Sub-County')], default='subcounty', max_length=20),
        ),
        migrations.AddField(
            model_name='landuserecord',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landuse_records', to='landuse.subcounties'),
        ),
        migrations.AlterUniqueTogether(
            name='landuserecord',
            unique_together={('county', 'subcounty', 'year', 'season')},
        ),
    ]
