# Generated by Django 5.2.11 on 2026-02-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landuse', '0002_alter_landuserecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropTypeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('county', 'County'), ('subcounty', 'Sub-County')], default='subcounty', max_length=20)),
                ('year', models.IntegerField()),
                ('season', models.CharField(blank=True, choices=[('long_rains', 'Long Rains'), ('short_rains', 'Short Rains')], max_length=20, null=True)),
                ('total_hectares', models.FloatField()),
                ('geoserver_link', models.URLField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='croptype_records', to='landuse.counties')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='croptype_records', to='landuse.subcounties')),
            ],
            options={
                'unique_together': {('county', 'subcounty', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='CropTypeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectares', models.FloatField()),
                ('percentage', models.FloatField()),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landuse.croptype')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='landuse.croptyperecord')),
            ],
            options={
                'unique_together': {('record', 'crop_type')},
            },
        ),
    ]
