# Generated by Django 5.2.11 on 2026-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landuse', '0003_croptype_croptyperecord_croptypeclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptyperecord',
            name='geoserver_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='landuserecord',
            name='geoserver_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
