# Generated by Django 5.2.11 on 2026-02-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landuse', '0004_alter_croptyperecord_geoserver_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptyperecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landuserecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
