# Generated by Django 5.2.11 on 2026-02-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landuse', '0005_croptyperecord_name_landuserecord_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croptyperecord',
            old_name='geoserver_link',
            new_name='geoserver_wms_layername',
        ),
        migrations.RenameField(
            model_name='landuserecord',
            old_name='geoserver_link',
            new_name='geoserver_wms_layername',
        ),
    ]
